package MortgageCalRefactor;

import java.text.NumberFormat;

public class MortgageReport {

    final  byte MONTHS_IN_YEAR = 12;
    private MortgageCalculation mortgagecal1;// since this report class generates report each differently for differnce instances of MortgageCalculation, that is the reason we have created a 
    //private field for holding the instantiation value of each MortgageCalculation object
    
      //creating a constructor of MortgageReport class to initialize MortgageCalculation type field of this class with the instance generated by the MortgageCalculation class.
      public MortgageReport(MortgageCalculation mortgagecalculation){
        this.mortgagecal1 = mortgagecalculation;
      }

      public void printMortgage() {

        double mortgage = mortgagecal1.calculateMortgage();
        String mortgageFormatted = NumberFormat.getCurrencyInstance().format(mortgage);
        System.out.println();
        System.out.println("MORTGAGE");
        System.out.println("--------");
        System.out.println("Monthly Payments: " + mortgageFormatted);
    }

    public void printPaymentSchedule() {
        System.out.println();
        System.out.println("PAYMENT SCHEDULE");
        System.out.println("----------------");
        
        mortgagecal1.getBalance();
    }

    
}
